### ISSUE TITLE
Ace only counts as 11, not switching to 1 when over 21.

### ISSUE THREAD

**Issue by RedburnDrift** [Pullolo/DiamondCasino#1]
Noticed that I when I got an 8, a 2, and an Ace, my total was 23. Should it not be 11?

**Comment by Pullolo** [comment]
My bad, I forgot about it, I will try to fix it next commit.

**Comment by Pullolo** [comment]
Should be now fixed 4263b46e2fcf516446d00a4e9364035fa7a77862 .
