### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by HoboBIll** [Pullolo/DiamondCasino#2]
First off I wanna say this plugin is awesome! it did end up ruining our servers economy when someone hit it big lol but who cares!

I wanna ask if you could possibly add bigger bet intervals for players who have millions? like maybe a bet $100,000 and 1M?

**Comment by Pullolo** [comment]
When i will have time I will try to implement it.

**Comment by Pullolo** [comment]
Added in a5c249c.

**Comment by HoboBIll** [comment]
> Added in [a5c249c](https://github.com/Pullolo/DiamondCasino/commit/a5c249c822938193efcb32e97af730b57ebe0300).

THANKSSS!
